apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:26.5.5
  startOptimized: false
  hostname:
    hostname: keycloak.ass-nss.jkuzel02.online
    strict: false
  http:
    httpEnabled: true
  proxy:
    headers: xforwarded
  db:
    vendor: postgres
    url: jdbc:postgresql://keycloak-postgres-rw:5432/keycloak
    usernameSecret:
      name: keycloak-postgres-app
      key: username
    passwordSecret:
      name: keycloak-postgres-app
      key: password
  bootstrapAdminUsername: admin
  bootstrapAdminPasswordSecret:
    name: keycloak-credentials
    key: admin-password
  ingress:
    enabled: false
