$TTL 3600
; Zone: jkuzel02.online. (#592020)
; File written on Sun Apr 12 01:47:35 2026
$ORIGIN jkuzel02.online.
@	IN SOA	ns1.webglobe.cz. root.webglobe.cz. (
	2026041203	  ; Serial
	28800     	  ; Refresh
	7200      	  ; Retry
	604800    	  ; Expire
	3600      	) ; Minimum
argocd.ass-nss     	3600	IN A    	1.1.1.1
ass-nss            	3600	IN A    	1.1.1.1
harbor.ass-nss     	3600	IN A    	1.1.1.1
longhorn.ass-nss   	3600	IN A    	1.1.1.1
keycloak.ass-nss   	3600	IN A    	1.1.1.1
vault.ass-nss      	3600	IN A    	1.1.1.1
