apiVersion: v1
kind: Service
metadata:
  name: webrag-worker-embed
  namespace: webrag
  labels:
    app: webrag-worker-embed
spec:
  selector:
    app: webrag-worker-embed
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
