apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: webrag-pg
  namespace: webrag
spec:
  instances: 3
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  storage:
    storageClass: longhorn
    size: 10Gi
  bootstrap:
    initdb:
      database: rag
      owner: rag
