apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: alertmanager-telegram
    creationPolicy: Owner
  data:
    - secretKey: bot-token
      remoteRef:
        key: alertmanager/telegram
        property: bot_token
    - secretKey: chat-id
      remoteRef:
        key: alertmanager/telegram
        property: chat_id
