instances:
  children:
    swarm_managers:
      hosts:
        swarm_node_0:
          ansible_host: swarm-node-0

        swarm_node_1:
          ansible_host: swarm-node-1

        swarm_node_2:
          ansible_host: swarm-node-2

    swarm_workers:
      hosts:
        swarm_ingress:
          ansible_host: 78.128.235.199

glusterfs_share_instances:
  children:
    swarm_managers:
