openstack_instances:
  children:
    network_share_instances:
      hosts:
        network_share_0:
          ansible_host: network-share-0
          
        network_share_1:
          ansible_host: network-share-1

        network_share_2:
          ansible_host: network-share-2

    docker_instances:
      children:
        swarm_managers:
          hosts:
            swarm_manager_0:
              ansible_host: swarm-manager-0

            swarm_manager_1:
              ansible_host: swarm-manager-1

            swarm_manager_2:
              ansible_host: swarm-manager-2

        swarm_workers:
          hosts:
            swarm_worker_0:
              ansible_host: swarm-worker-0

            swarm_worker_1:
              ansible_host: swarm-worker-1
