instances:
  children:
    proxy:
      hosts:
        proxy:
          ansible_host: proxy
    workers:
      hosts:
        site_a:
          ansible_host: site-a
        site_b:
          ansible_host: site-b