apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: harbor-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: client_secret
      remoteRef:
        key: oidc/harbor
        property: client_secret
