apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: test
  namespace: jkuzel02-prometheus
  labels:
    prometheus: test
spec:
  serviceMonitorSelector: { matchLabels: {} }
  podMonitorSelector: { matchLabels: {} }

  containers:
    - name: prometheus
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: { drop: ["ALL"] }

    - name: config-reloader
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: { drop: ["ALL"] }

  initContainers:
    - name: init-config-reloader
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: { drop: ["ALL"] }

  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 2000
    seccompProfile: { type: RuntimeDefault }
