# 1. THE WEBPAGE CONTENT
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
  namespace: jkuzel02-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>e-INFRA CZ Welcome</title>
        <style>
            body { background-color: #f4f4f4; font-family: sans-serif; text-align: center; padding-top: 50px; }
            h1 { color: #0055a4; }
        </style>
    </head>
    <body>
        <h1>Hi from e-INFRA</h1>
        <h2>NO NIC!</h2>
    </body>
    </html>
