alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  admin:
    existingSecret: grafana-credentials
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    type: sts
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection
  envFromSecrets:
    - name: grafana-oidc-secret
  grafana.ini:
    server:
      root_url: https://grafana.ass-nss.jkuzel02.online
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      client_id: grafana
      client_secret: $__env{client_secret}
      scopes: openid profile email
      auth_url: https://keycloak.ass-nss.jkuzel02.online/realms/ass-nss/protocol/openid-connect/auth
      token_url: https://keycloak.ass-nss.jkuzel02.online/realms/ass-nss/protocol/openid-connect/token
      api_url: https://keycloak.ass-nss.jkuzel02.online/realms/ass-nss/protocol/openid-connect/userinfo
      role_attribute_path: contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'analytic') && 'Viewer'
      role_attribute_strict: true

nodeExporter:
  operatingSystems:
    aix:
      enabled: false
    darwin:
      enabled: false

prometheus:
  prometheusSpec:
    retention: 14d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
