# Wave 15 — Longhorn config: ExternalSecrets + IngressRoute (after ESO wave 9, Keycloak wave 12)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  revisionHistoryLimit: 0
  project: infrastructure
  source:
    repoURL: https://github.com/ASS-NSS-Project/enc-ass-nss-project
    targetRevision: kost
    path: argocd/apps/longhorn/config
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
