apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: oidc/traefik
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: oidc/traefik
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: oidc/traefik
        property: cookie_secret
