apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-auth
  namespace: longhorn-system
spec:
  plugin:
    keycloakopenid:
      KeycloakURL: https://keycloak.nss.jkzl.eu
      ClientID: $KEYCLOAK_CLIENT_ID
      ClientSecret: $KEYCLOAK_CLIENT_SECRET
      KeycloakRealm: ass-nss-project
      Scope: openid
      TokenCookieName: AUTH_TOKEN
      UseAuthHeader: "false"
      AllowedGroups:
        - admin
