apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-basic-auth
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: longhorn-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: longhorn
        property: htpasswd
