apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ass-nss-vault-tls
  namespace: traefik
spec:
  secretName: ass-nss-vault-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - vault.ass-nss.jkuzel02.online
