apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ass-nss-grafana-tls
  namespace: traefik
spec:
  secretName: ass-nss-grafana-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - grafana.ass-nss.jkuzel02.online
