apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nss-argocd-tls
  namespace: traefik
spec:
  secretName: nss-argocd-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - argocd.nss.jkzl.eu
