apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nss-longhorn-tls
  namespace: longhorn-system
spec:
  secretName: nss-longhorn-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - longhorn.nss.jkzl.eu
