apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nss-rabbitmq-tls
  namespace: traefik
spec:
  secretName: nss-rabbitmq-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - rabbitmq.nss.jkzl.eu
