apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Core cluster infrastructure
  sourceRepos:
    - https://github.com/ASS-NSS-Project/site-infra
    - https://traefik.github.io/charts
    - https://charts.jetstack.io
    - https://charts.longhorn.io
    - https://cloudnative-pg.github.io/charts
    - https://helm.releases.hashicorp.com
    - https://charts.external-secrets.io
    - https://oauth2-proxy.github.io/manifests
    - https://qdrant.github.io/qdrant-helm
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: cnpg-system
    - server: https://kubernetes.default.svc
      namespace: keycloak
    - server: https://kubernetes.default.svc
      namespace: longhorn-system
    - server: https://kubernetes.default.svc
      namespace: traefik
    - server: https://kubernetes.default.svc
      namespace: vault
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: external-secrets
    - server: https://kubernetes.default.svc
      namespace: oauth2-proxy
    - server: https://kubernetes.default.svc
      namespace: rabbitmq-system
    - server: https://kubernetes.default.svc
      namespace: qdrant
    - server: https://kubernetes.default.svc
      namespace: rag-system
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
