apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-credentials
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-credentials
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: oidc/oauth2-proxy
        property: client_id
    - secretKey: client-secret
      remoteRef:
        key: oidc/oauth2-proxy
        property: client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: oidc/oauth2-proxy-cookie
        property: cookie_secret
