- name: Configure Ganesha Export
  ansible.builtin.copy:
    dest: /etc/ganesha/ganesha.conf
    content: |
      EXPORT
      {
          Export_Id = 101;
          Path = "/{{ glusterfs_volume_name }}";
          Pseudo = "/{{ glusterfs_volume_name }}";
          Access_Type = RW;
          Protocols = 3, 4;
          Transports = TCP;
          Squash = No_Root_Squash;
          FSAL {
              Name = GLUSTER;
              Volume = "{{ glusterfs_volume_name }}";
              Hostname = "localhost";
          }
      }

- name: Restart NFS-Ganesha
  ansible.builtin.service:
    name: nfs-ganesha
    state: restarted
    enabled: true
