- name: Format the Disks and Prepare Them as Bricks
  import_tasks: 01-PVs-Bricks.yml

- name: Setup GlusterFS
  import_tasks: 02-GlusterFS-Setup.yml
    
- name: Handle GlusterFS Intiatilization
  import_tasks: 03-GlusterFS-Init.yml

- name: Mount GlusterFS
  import_tasks: 04-Mount-GlusterFS.yml
