- name:         Manage Instances System
  hosts:        openstack_instances
  gather_facts: false
  become:       true
  roles: 
    - { role: local.system, tags: system }

- name:         Setup GlusterFS for NFS Shares for Docker Swarm Volumes Persistency
  hosts:        network_share_instances
  gather_facts: false
  become:       true
  roles:
    - { role: local.glusterfs, tags: glusterfs }

- name:         Setup GlusterFS Clients on the Docker Instances for HA Volume Access
  hosts:        docker_instances
  gather_facts: false
  become:       true
  roles:
    - { role: local.glusterfs-client, tags: [ glusterfs, glusterfs-client ] }

- name:         Setup Docker on the Instances (Docker Swarm Mode Enabled)
  hosts:        docker_instances
  gather_facts: true
  become:       false
  roles:
    - { role: local.docker,           tags: docker }
    - { role: local.docker-bootstrap, tags: [ docker, bootstrap ] }
    