- name:         Manage Instances System
  hosts:        instances
  gather_facts: false
  become:       true
  roles: 
    - { role: local.system, tags: system }

- name:         Setup Docker on the Instances (Docker Swarm Mode Enabled)
  hosts:        swarm_managers
  gather_facts: true
  become:       true
  roles:
    - { role: local.docker, tags: docker }

- name:         Setup GlusterFS Share for Docker Swarm Volumes Persistency
  hosts:        swarm_managers
  gather_facts: false
  become:       true
  roles:
    - { role: local.glusterfs, tags: glusterfs }

- name:         Bootstrap Basic Stack
  hosts:        swarm_managers
  gather_facts: true
  become:       false
  roles:
    - { role: local.docker-bootstrap, tags: bootstrap }
    
- name:         Clone GitHub repo for the RAG System App
  hosts:        swarm_0
  gather_facts: true
  become:       false
  tags:         rag
  tasks:
    - name: Clone the repo
      ansible.builtin.git:
        repo: 'https://github.com/jkuzel02/rag_system.git'
        dest: "{{ ansible_facts['env']['HOME'] }}/rag_system"
        version: main

    - name: Copy the .env file
      ansible.builtin.copy:
        src: "files/.env"
        dest: "{{ ansible_facts['env']['HOME'] }}/rag_system/.env"
        owner: "{{ ansible_facts['env']['USER'] }}"
        group: "{{ ansible_facts['env']['USER'] }}"
