- name: Promote workers to managers if they joined with wrong role
  ansible.builtin.shell: |
    docker node promote {{ item }}
  loop: "{{ groups['swarm_managers'] }}"
  when: 
    - inventory_hostname == groups['swarm_managers'][0] # Only run on the Leader
    - item != inventory_hostname # Don't try to promote yourself
  register: promotion_output
  changed_when: "'promoted' in promotion_output.stdout"
  failed_when: false