- name: Set role flags for all nodes
  ansible.builtin.set_fact:
    is_manager: >-
      {{ 
        'swarm_managers' in group_names or 
        'swarm_masters' in group_names or
        'docker_swarm_managers' in group_names or 
        'docker_swarm_masters' in group_names or 
        'managers' in group_names or
        'masters' in group_names
      }}
    is_worker: >-
      {{ 
        'swarm_workers' in group_names or 
        'docker_swarm_workers' in group_names or
        'workers' in group_names
      }}
      