# Wave 21 — RAG system (depends on: cnpg wave 10, rabbitmq-operator-helm wave 19, qdrant-helm wave 20)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webrag-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "19"
spec:
  revisionHistoryLimit: 0
  project: webrag
  source:
    repoURL: https://github.com/ASS-NSS-Project/enc-ass-nss-project
    targetRevision: kost
    path: argocd/apps/webrag/config
  destination:
    server: https://kubernetes.default.svc
    namespace: webrag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
