# Wave 3 — ClusterIssuers + Certificates (depends on cert-manager wave 2)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  revisionHistoryLimit: 0
  project: infrastructure
  source:
    repoURL: https://github.com/ASS-NSS-Project/infra
    targetRevision: kost
    path: argocd/apps/cert-manager/config
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
