# Wave 2 — cert-manager (Helm chart + values from git)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  revisionHistoryLimit: 0
  project: infrastructure
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: ">=1.16.0"
      helm:
        valueFiles:
          - $values/argocd/apps/cert-manager/helm/values.yaml
    - repoURL: https://github.com/ASS-NSS-Project/infra
      targetRevision: kost
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
