# Wave 11 — Keycloak Operator (CRDs + controller; after cnpg wave 10, before keycloak-config wave 12)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  revisionHistoryLimit: 0
  project: infrastructure
  source:
    repoURL: https://github.com/ASS-NSS-Project/enc-ass-nss-project
    targetRevision: kost
    path: argocd/apps/keycloak/keycloak-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
