# Auto-generated by Terraform on every `terraform apply` — do not edit manually.
all:
  children:
    k3s_cluster:
      children:
        control_plane:
          children:
            cp_primary:
              hosts:
                cp-0:
                  ansible_host: ${cp0_fip}

            cp_followers:
              hosts:
%{ for i, ip in cp_ips ~}
%{ if i > 0 ~}
                cp-${i}:
                  ansible_host: ${ip}
%{ endif ~}
%{ endfor ~}

        workers:
          hosts:
%{ for i, ip in worker_ips ~}
            worker-${i}:
              ansible_host: ${ip}
%{ endfor ~}
