# Auto-generated by Terraform on every `terraform apply` — do not edit manually.
# These variables are derived from live OpenStack resources.

# API LB public floating IP — used in kubeconfig and k3s TLS SANs
k3s_api_lb_fip: "${api_lb_fip}"
